app/app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sample/', include("sample.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ↓追加
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/sample/urls.py
from django.urls import path
from .views.sample import *

app_name = 'sample'
urlpatterns = [
    path('list', SampleView.as_view(), name="list"),

]

app/agent/models/blacklist_seller.py
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
from datetime import datetime as dt
from datetime import timedelta as delta
from sqlalchemy import Column, String,Text ,DateTime, Float, Integer, ForeignKey, Boolean, func, update
from sqlalchemy.dialects.mysql import LONGTEXT
from sqlalchemy.sql.functions import current_timestamp
from sqlalchemy.orm import relationship
from sqlalchemy.sql.type_api import STRINGTYPE
from sqlalchemy_utils import UUIDType
from pytz import timezone

from common.database import Base, get_ulid, session
from common.logger import set_logger
from common.utility import now_timestamp


class BlacklistSeller(Base):
    __tablename__ = 't_blacklist_seller'
    mysql_charset = 'utf8mb4',
    mysql_collate = 'utf8mb4_unicode_ci'

    id = Column('id', Integer, primary_key=True)
    account_id = Column('account_id', String(100), nullable=False)
    seller_name = Column('seller_name', String(64), nullable=False)
    created_at = Column('created_at', DateTime, nullable=False,
                        server_default=current_timestamp())
    updated_at = Column('updated_at', DateTime, nullable=False,
                        default=current_timestamp(), onupdate=func.utc_timestamp())

app/agent/models/blacklist_word.py
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
from datetime import datetime as dt
from datetime import timedelta as delta
from sqlalchemy import Column, String,Text ,DateTime, Float, Integer, ForeignKey, Boolean, func, update
from sqlalchemy.dialects.mysql import LONGTEXT
from sqlalchemy.sql.functions import current_timestamp
from sqlalchemy.orm import relationship
from sqlalchemy.sql.type_api import STRINGTYPE
from sqlalchemy_utils import UUIDType
from pytz import timezone

from common.database import Base, get_ulid, session
from common.logger import set_logger
from common.utility import now_timestamp


class BlacklistWord(Base):
    __tablename__ = 't_blacklist_word'
    mysql_charset = 'utf8mb4',
    mysql_collate = 'utf8mb4_unicode_ci'

    id = Column('id', Integer, primary_key=True)
    account_id = Column('account_id', String(100), nullable=False)
    blacklist_word = Column('blacklist_word', String(16), nullable=False)
    created_at = Column('created_at', DateTime, nullable=False,
                        server_default=current_timestamp())
    updated_at = Column('updated_at', DateTime, nullable=False,
                        default=current_timestamp(), onupdate=func.utc_timestamp())

app/agent/models/fetch_url.py
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
from datetime import datetime as dt
from datetime import timedelta as delta
from sqlalchemy import Column, String,Text ,DateTime, Float, Integer, ForeignKey, Boolean, func, update
from sqlalchemy.dialects.mysql import LONGTEXT
from sqlalchemy.sql.functions import current_timestamp
from sqlalchemy.orm import relationship
from sqlalchemy.sql.type_api import STRINGTYPE
from sqlalchemy_utils import UUIDType
from pytz import timezone

from common.database import Base, get_ulid, session
from common.logger import set_logger
from common.utility import now_timestamp


class FetchUrl(Base):
    __tablename__ = 't_fetch_url'
    mysql_charset = 'utf8mb4',
    mysql_collate = 'utf8mb4_unicode_ci'

    id = Column('id', Integer, primary_key=True)
    account_id = Column('account_id', String(100), nullable=False)
    url = Column('url', String(64), nullable=False)
    is_completed = Column('is_completed', Boolean, default=False)
    created_at = Column('created_at', DateTime, nullable=False,
                        server_default=current_timestamp())
    updated_at = Column('updated_at', DateTime, nullable=False,
                        default=current_timestamp(), onupdate=func.utc_timestamp())

app/agent/models/profit.py
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
from datetime import datetime as dt
from datetime import timedelta as delta
from sqlalchemy import Column, String,Text ,DateTime, Float, Integer, ForeignKey, Boolean, func, update
from sqlalchemy.dialects.mysql import LONGTEXT
from sqlalchemy.sql.functions import current_timestamp
from sqlalchemy.orm import relationship
from sqlalchemy.sql.type_api import STRINGTYPE
from sqlalchemy_utils import UUIDType
from pytz import timezone

from common.database import Base, get_ulid, session
from common.logger import set_logger
from common.utility import now_timestamp


class Profit(Base):
    __tablename__ = 't_profit'
    mysql_charset = 'utf8mb4',
    mysql_collate = 'utf8mb4_unicode_ci'

    id = Column('id', Integer, primary_key=True)
    account_id = Column('account_id', String(100), nullable=False)
    base_price = Column('base_price', Integer, default=0)
    profit = Column('profit', Integer, default=0)
    created_at = Column('created_at', DateTime, nullable=False,
                        server_default=current_timestamp())
    updated_at = Column('updated_at', DateTime, nullable=False,
                        default=current_timestamp(), onupdate=func.utc_timestamp())

app/agent/models/replace_word.py
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
from datetime import datetime as dt
from datetime import timedelta as delta
from sqlalchemy import Column, String,Text ,DateTime, Float, Integer, ForeignKey, Boolean, func, update
from sqlalchemy.dialects.mysql import LONGTEXT
from sqlalchemy.sql.functions import current_timestamp
from sqlalchemy.orm import relationship
from sqlalchemy.sql.type_api import STRINGTYPE
from sqlalchemy_utils import UUIDType
from pytz import timezone

from common.database import Base, get_ulid, session
from common.logger import set_logger
from common.utility import now_timestamp


class ReplaceWord(Base):
    __tablename__ = 't_replace_word'
    mysql_charset = 'utf8mb4',
    mysql_collate = 'utf8mb4_unicode_ci'

    id = Column('id', Integer, primary_key=True)
    account_id = Column('account_id', String(100), nullable=False)
    base_word = Column('base_word', String(128), nullable=False)
    replace_word = Column('replace_word', String(128), nullable=True)
    is_alert = Column('is_alert', Boolean, default=False)
    created_at = Column('created_at', DateTime, nullable=False,
                        server_default=current_timestamp())
    updated_at = Column('updated_at', DateTime, nullable=False,
                        default=current_timestamp(), onupdate=func.utc_timestamp())

app/agent/models/search_word.py
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
from datetime import datetime as dt
from datetime import timedelta as delta
from sqlalchemy import Column, String,Text ,DateTime, Float, Integer, ForeignKey, Boolean, func, update
from sqlalchemy.dialects.mysql import LONGTEXT
from sqlalchemy.sql.functions import current_timestamp
from sqlalchemy.orm import relationship
from sqlalchemy.sql.type_api import STRINGTYPE
from sqlalchemy_utils import UUIDType
from pytz import timezone

from common.database import Base, get_ulid, session
from common.logger import set_logger
from common.utility import now_timestamp


class SearchWord(Base):
    __tablename__ = 't_search_word'
    mysql_charset = 'utf8mb4',
    mysql_collate = 'utf8mb4_unicode_ci'

    id = Column('id', Integer, primary_key=True)
    account_id = Column('account_id', String(100), nullable=False)
    search_word = Column('search_word', String(64), nullable=False)
    search_site = Column('search_site', String(10), nullable=False)
    is_completed = Column('is_completed', Boolean, default=False)
    created_at = Column('created_at', DateTime, nullable=False,
                        server_default=current_timestamp())
    updated_at = Column('updated_at', DateTime, nullable=False,
                        default=current_timestamp(), onupdate=func.utc_timestamp())

app/users/models.py
from config.const import SELECTION
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.utils import timezone
import uuid as uuid_lib


class YahooAccount(models.Model):
    yahoo_account_id = models.CharField(_('ヤフオクアカウント'), max_length=50, blank=True)
    yahoo_pass = models.CharField(_('ヤフオクパスワード'), max_length=20, blank=True)
    def __str__(self):
        return self.yahoo_account_id

    class Meta:
        verbose_name = _('ヤフオクアカウント')
        verbose_name_plural = _('ヤフオクアカウント')

class UserManager(UserManager):
    '''
    カスタムUserモデルを作成したため、UserManagerもオーバーライドする
    '''    
    def _create_user(self, account_id, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not account_id:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        account_id = self.model.normalize_username(account_id)
        user = self.model(account_id=account_id, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self, account_id, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(account_id, email, password, **extra_fields)
    
    def create_superuser(self, account_id, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(account_id, email, password, **extra_fields)
    
    # 各種初期設定を作成
    def init_settings(self, account_id):
        pass
    
class User(AbstractBaseUser, PermissionsMixin):
    """　
    カスタムUserモデル
    """
    uuid = models.UUIDField(default=uuid_lib.uuid4,
                            primary_key=True, editable=False)
    username_validator = UnicodeUsernameValidator()

    account_id = models.CharField(
        _('アカウントID'),
        max_length=150,
        unique=True,
        help_text=_(
            'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that account_id already exists."),
        },
    )
    full_name = models.CharField(_('氏名'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    account_count=models.IntegerField(_('最大アカウント数'),blank=True,null=True)
    yahoo_account_id = models.ManyToManyField(
        YahooAccount,
        verbose_name=_('ヤフオクアカウント'),
        blank=True,
        help_text=_('ヤフオクアカウントを登録'),
        related_name="user_set",
        related_query_name="user",
    )
    plan = models.CharField(_('プラン'), max_length=20, choices=SELECTION.PLAN,default=SELECTION.PLAN[0][0])
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    begin_crawle_at = models.DateTimeField(_('クロール開始日時'), null=True)
    crawled_at = models.DateTimeField(_('最終クロール日時'), null=True)
    is_crawle = models.BooleanField(_('is_crawle'), null=True)
    syuppin_mode_at = models.DateTimeField(_('最終出品モード起動日時'), null=True)
    torihiki_mode_at = models.DateTimeField(_('最終取引モード起動日時'), null=True)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'account_id'
    REQUIRED_FIELDS = ['email', ]

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    # 既存メソッドの変更
    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.full_name
    

app/sample/forms/item_search.py
from django import forms
from bootstrap_modal_forms.forms import BSModalForm
from django.forms.fields import ChoiceField
from django.forms import TextInput

class ItemSearchForm(forms.Form):

    # Amazon本体
    SELL_AMAZON_CHOICE = {
        ('0', 'すべて'), # 0だと画面先頭に表示されないので000にしています。
        ('1', 'なし'),
        ('2', 'あり'),
    }
    sell_amazon = forms.ChoiceField(label='Amazon販売', 
                                    widget=forms.RadioSelect, choices=SELL_AMAZON_CHOICE, initial=0)

    # カート価格 下限
    cart_price_label = forms.CharField(label="カート価格")
    cart_price_min = forms.CharField(required=False,
                                    widget=forms.TextInput(attrs={
                                        'placeholder': 'Min',
                                        'pattern': '^[0-9]+$'}))
    cart_price_max = forms.CharField(required=False,
                                    widget=forms.TextInput(attrs={
                                        'placeholder': 'Max',
                                        'pattern': '^[0-9]+$'}))
    # 90日なし率
    non_amazon_90days_label = forms.CharField(label="90日なし率")
    non_amazon_90days_min = forms.CharField(required=False,
                                    widget=forms.TextInput(attrs={
                                        'placeholder': 'Min',
                                        'pattern': '^[0-9]+$'}))
    non_amazon_90days_max = forms.CharField(required=False,
                                    widget=forms.TextInput(attrs={
                                        'placeholder': 'Max',
                                        'pattern': '^[0-9]+$'}))

    # 単品利益
    profit_label = forms.CharField(label="利益")
    profit_min = forms.CharField(required=False,
                                    widget=forms.TextInput(attrs={
                                        'placeholder': 'Min',
                                        'pattern': '^[0-9]+$'}))
    profit_max = forms.CharField(required=False,
                                    widget=forms.TextInput(attrs={
                                        'placeholder': 'Max',
                                        'pattern': '^[0-9]+$'}))

    # 利益率 下限・上限
    profit_rate_label = forms.CharField(label="利益率")  # maxlength値は？
    profit_rate_min = forms.CharField(required=False,
                                    widget=forms.TextInput(attrs={
                                        'placeholder': 'Min',
                                        'pattern': '^[0-9]+$'}))
    profit_rate_max = forms.CharField(required=False,
                                    widget=forms.TextInput(attrs={
                                        'placeholder': 'Max',
                                        'pattern': '^[0-9]+$'}))

    SINGLE_CHOICE = [(True, "")]
    item_quantity_exclusion = forms.MultipleChoiceField(
        label="セット商品除外",
        required=False,
        disabled=False,
        initial=[],
        choices=SINGLE_CHOICE,
        widget=forms.CheckboxSelectMultiple(attrs={}))

app/sample/views/sample.py
from django.shortcuts import render
from django_tables2 import SingleTableView, RequestConfig
from ..models.sample import *
from ..tables.sample import * 
from ..forms.item_search import *

class SampleView(SingleTableView):
    table_class = SampleTable
    template_name = "sample/item_list.html"

    # テーブルを生成するための情報を取得
    def get(self, request, *args, **kwargs):
        # Modelからすべての情報を取得
        sample_model_query = SampleModel.objects
        
        # item_nameでフィルタ
        item_name = request.GET.get("item_name")
        if item_name == None or item_name == "":
            # 検索条件が未指定の場合は全件表示
            sample_objects = sample_model_query.all()
        else:
            sample_objects = sample_model_query.filter(item_name=item_name).all()
        
        # Tableデータを生成
        table = SampleTable(sample_objects)
        
        # HTMLに出力する内容をセット
        context = {"table": table, 
                   "record_count": sample_objects.count()} # レコード件数
        
        # HTMLを出力
        return render(request, self.template_name, context)
        
   

app/templates/setting/asin.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}ASIN設定{% endblock %}

{% block contents %}
 <section>
	<div class="section-header">
		<h1> ASIN設定 </h1>
	</div>
	<p></p>
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-12 col-lg-12">
				<div class="card">
					<div>
						<nav class="nav nav-tabs">
							<a class="nav-link active" href="{% url 'setting:asin' %}">ASIN登録</a>
							<a class="nav-link" href="{% url 'setting:exclude-asin' %}">除外ASIN</a>
							<a class="nav-link" href="{% url 'setting:exclude-word' %}">除外ワード</a>
						  </nav>

					</div>
					<div class="card-body">
						{% if form.errors %}
							{% for field in form %}
								<div class="text-danger">
									{% for error in field.errors %}
										{{field.label}}: {{ error|escape }}
									{% endfor %}
								</div>
							{% endfor %}
						{% endif %}
						{% if messages %}
							<ul class="messages_ul">
								{% for message in messages %}
									<li class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ message }}</li>
								{% endfor %}
							</ul>
						{% endif %}
						<form method="POST">
							{% csrf_token %}
							{{ form.non_field_errors }}
							<div class='col-offset-2 col-10'>
								{%if form.submit %}
								<button type='submit' class='btn btn-primary'>登録</button>
								{% endif %}
							</div>
							<div class='form-group'>
								<span class="col-4 control-label" >{{ form.yahoo_account_id.label }}</span>
								{% if form.yahoo_account_id.value != None %}
									<div class='col-4'><input class="form-control" name="yahoo_account_id" value="{{ form.yahoo_account_id.value }}" readonly></input></div>
								{% else %}
									<div class='col-4'>{{ form.yahoo_account_id|add_class:"form-control" }}</div>
								{% endif %}
							</div>
							<div class='form-group'>
								<labal class='col-4 control-label'>{{ form.asin_group_id.label }}（重複しないわかりやすい名称をつけてください）</labla>
								{% if form.asin_group_id.value != None %}
									<div class='col-4'><input class="form-control" name="asin_group_id"  id="id_asin_group_id" value="{{ form.asin_group_id.value }}" readonly></input></div>
								{% else %}
									<div class='col-4'><input class="form-control" name="asin_group_id" id="id_asin_group_id" value=""></input></div>
								{% endif %}
							</div>
							<div class='form-group'>
								<labal class='col-4 control-label'>{{ form.asins.label }}（最大１万件まで登録可能）</labla>
								<div class='col-8'>{{ form.asins|add_class:"textarea-wide form-control" }}</div>
							</div>

							<div class='col-offset-2 col-10'>
								{%if form.submit %}
								<button type='submit' class='btn btn-primary'>登録</button>
								{% endif %}
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

app/templates/setting/blacklist_seller.html
{% extends 'base.html' %}
{% load static %}

{% block title %}NGワード・除外セラー設定{% endblock %}

{% block contents %}
 <section>
	<div class="section-header">
		<h1> NGワード・除外セラー設定 </h1>
	</div>
	<p></p>
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-12 col-lg-12">
				<div class="card">
					<div>
						<nav class="nav nav-tabs">
							<a class="nav-link" href="{% url 'setting:blacklist-word' %}">NGワード登録</a>
							<a class="nav-link active" href="{% url 'setting:blacklist-seller' %}">除外セラー登録</a>
						</nav>

					</div>
					<div>
						{% if form.errors %}
							{% for field in form %}
								<div class="text-danger">
									{% for error in field.errors %}
										{{field.label}}: {{ error|escape }}
									{% endfor %}
								</div>
							{% endfor %}
						{% endif %}
						{% if error_message %}
							<div class="text-danger">
									{{error_message}}
							</div>
						{% endif %}
						{% if result %}
							<div class="text-primary">
								{{ form.blacklist_sellers.label }} : {{result}}を登録しました。
							</div>
						{% endif %}
					</div>
					<div class="card-body">
						<form method="POST">
							{% csrf_token %}
							{{ form.non_field_errors }}
							<div class='col-offset-2 col-10'>
								<button type='submit' class='btn btn-primary'>登録</button>
							</div>
							<div class='form-group mt-2'>
								<labal class='col-4 control-label'>{{ form.blacklist_sellers.label }}</labla>
								<div class='col-8'>{{ form.blacklist_sellers}}</div>
							</div>

							<div class='col-offset-2 col-10'>
								<button type='submit' class='btn btn-primary'>登録</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

app/templates/setting/blacklist_word.html
{% extends 'base.html' %}
{% load static %}

{% block title %}NGワード・除外セラー設定{% endblock %}

{% block contents %}
 <section>
	<div class="section-header">
		<h1> NGワード・除外セラー設定 </h1>
	</div>
	<p></p>
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-12 col-lg-12">
				<div class="card">
					<div>
						<nav class="nav nav-tabs">
							<a class="nav-link active" href="{% url 'setting:blacklist-word' %}">NGワード登録</a>
							<a class="nav-link" href="{% url 'setting:blacklist-seller' %}">除外セラー登録</a>
						</nav>

					</div>
					<div>
						{% if form.errors %}
							{% for field in form %}
								<div class="text-danger">
									{% for error in field.errors %}
										{{field.label}}: {{ error|escape }}
									{% endfor %}
								</div>
							{% endfor %}
						{% endif %}
						{% if error_message %}
							<div class="text-danger">
									{{error_message}}
							</div>
						{% endif %}
						{% if result %}
							<div class="text-primary">
								{{ form.blacklist_words.label }} : {{result}}を登録しました。
							</div>
						{% endif %}
					</div>
					<div class="card-body">
						<form method="POST">
							{% csrf_token %}
							{{ form.non_field_errors }}
							
							<div class='col-offset-2 col-10'>
								<button type='submit' class='btn btn-primary'>登録</button>
							</div>
							<div class='form-group mt-2'>
								<labal class='col-4 control-label'>{{ form.blacklist_words.label }}</labla>
								<div class='col-8'>{{ form.blacklist_words}}</div>
							</div>

							<div class='col-offset-2 col-10'>
								<button type='submit' class='btn btn-primary'>登録</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

app/templates/setting/eval_setting.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}評価設定{% endblock %}

{% block header %}
      
{% endblock %}

{% block contents %}
	<div class="section-header">
		<h1> 評価設定 </h1>
	</div>
    <div class="row">
        <div class="col-md-12">
            <div class="content-box-large">
               <div class="card">
                    <div class="card-body">
                        <form id="main-form" class="form-horizontal" role="form" method="POST">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            {% for field in form %}
                                <div class="form-group">
                                    <div>
                                        <label for="{{ field.id_for_label }}" class="col-4 control-label">{{ field.label_tag}}</label>
                                        <div class="col-4">{{ field|add_class:"form-control" }}</div>
                                        {{ field.errors }}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">登録</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        // ヤフオクアカウント変更時に再度GET
        $("#id_yahoo_account_id").change(function(){
            let form = $('#main-form');
            $("[name='csrfmiddlewaretoken']").remove()
            form.attr("method","GET"); // GETに変更
            form.submit();
        });
    </script>
{% endblock %}

app/templates/setting/price_setting.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}価格設定{% endblock %}
{% block contents %}
     <section>
        <div class="section-header">
            <h1> 出品価格設定 </h1>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <form id="main-form" class="form-inline" role="form" method="POST">
                                {% csrf_token %}
                                {{ form.non_field_errors }}
                                <div class="mt-2">
                                    <div class='form-group'>
                                        <span class="mr-2" >ヤフオクアカウント</span>
                                        <div>{{ form.yahoo_account_id|add_class:"form-control" }}</div>
                                    </div>
                                </dov>
                                <div class="mt-2">
                                    <div class='form-group'>
                                        <span class="mr-2" >レンジ1</span>
                                        <div>{{ form.price_range1|add_class:"form-control" }}</div>　→　
                                        <div>{{ form.price_rate1|add_class:"form-control" }}</div>
                                    </div>
                                </dov>
                                <div class="mt-2">
                                    <div class='form-group'>
                                        <span class="mr-2">レンジ2</span>
                                        <div>{{ form.price_range2|add_class:"form-control" }}</div>　→　
                                        <div>{{ form.price_rate2|add_class:"form-control" }}</div>
                                    </div>
                                </div>
                                <div class="mt-2">
                                    <div class='form-group'>
                                        <span class="mr-2">レンジ3</span>
                                        <div>{{ form.price_range3|add_class:"form-control" }}</div>　→　
                                        <div>{{ form.price_rate3|add_class:"form-control" }}</div>
                                    </div>
                                </div>
                                <div class="mt-2">
                                    <div class='form-group'>
                                        <span class="mr-2">レンジ4</span>
                                        <div>{{ form.price_range4|add_class:"form-control" }}</div>　→　
                                        <div>{{ form.price_rate4|add_class:"form-control" }}</div>
                                    </div>
                                </div>
                                <div class="mt-2">
                                    <div class='form-group'>
                                        <span class="mr-2">レンジ5</span>
                                        <div>{{ form.price_range5|add_class:"form-control" }}</div>　→　
                                        <div>{{ form.price_rate5|add_class:"form-control" }}</div>
                                    </div>
                                </div>
                                <div class="mt-2">
                                    <div class='form-group'>
                                        <span class="mr-2">開始価格と即決価格の差額</span>
                                        <div>{{ form.sokketsu_price_offset|add_class:"form-control" }}</div>
                                    </div>
                                </div>
                                <div class="col-sm-offset-2 col-sm-10 mt-2">
                                    <button type="submit" class="btn btn-primary">登録</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block script %}
    <script>
        // ヤフオクアカウント変更時に再度GET
        $("#id_yahoo_account_id").change(function(){
            let form = $('#main-form');
            $("[name='csrfmiddlewaretoken']").remove()
            form.attr("method","GET"); // GETに変更
            form.submit();
        });
    </script>
{% endblock %}