app/app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sample/', include("sample.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ↓追加
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/sample/urls.py
from django.urls import path
from .views.sample import *

app_name = 'sample'
urlpatterns = [
    path('list', SampleView.as_view(), name="list"),

]

app/users/urls.py
from django.urls import path
from .views.password_change import *
from .views.password_change_done import *

app_name = 'users'
urlpatterns = [
    path('password_change/', UserPasswordChangeView.as_view(), name="password_change"),
    path('password_change/done/', UserPasswordChangeDoneView.as_view(), name="password_change_done")
]

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja-JP">

<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>{% block title %}{% endblock %}</title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  

  <!-- CSS Libraries -->

  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/components.css' %}">
  <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
  <link rel="stylesheet" href="{% static 'handsontable/handsontable.min.css' %}">
  <link href="{% static 'css/my_styles.css' %}" rel="stylesheet">
  <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}">
  {% block head %}{% endblock %}
</head>
{%block modal%}{%endblock%}

<body>
  <div id="app">
    <div class="main-wrapper">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">

          </ul>
        </form>
        <ul class="navbar-nav navbar-right">
          <li class="dropdown dropdown-list-toggle">
            <div class="nav-link nav-link-lg nav-link-user">
              {% comment %} <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{% static 'assets/img/avatar/avatar-1.png' %}" class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block">{{ user.account_id }}</div>
              </a> {% endcomment %}
              {% comment %} <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{% url 'mypage:mypage' %}"><i class="far fa-address-card"></i> マイページ</a>
                <a class="dropdown-item" href="{% url 'users:password_change' %}"><i class="far fa-address-card"></i>
                  パスワード変更</a>
                <a class="dropdown-item" href="{% url 'mypage:logout' %}"><i class="fas fa-door-open"></i> ログアウト</a>
                {% if user.is_superuser %}
                <a class="dropdown-item" href="/admin"><i class="fas fa-user-lock"></i> 管理者ページ</a>
                {% endif %}
              </div> {% endcomment %}
            </div>
          </li>
        </ul>
      </nav>
      <div class="main-sidebar">
        <aside id="sidebar-wrapper">
          <div class="sidebar-brand">
            <a href=""><i></i>Django Sample</a>
          </div>
          <div class="sidebar-brand sidebar-brand-sm">
            <a href="#">D・S</a>
          </div>
          <ul class="sidebar-menu">
            <li class="nav-item">
               <a href="#" data-toggle="dropdown" class="nav-link">
              <i
                  class="fas fa-store"></i><span>商品管理</span></a>
              <ul class=""></a>
                <li><a class="nav-link" href="{% url 'sample:list' %}"><i class="far fa-file-word"></i>商品一覧</a></li>
              </ul>
            </li>
          
            {% comment %} <li class="nav-item">
              <a href="#" data-toggle="dropdown" class="nav-link"><i class="fas fa-cog"></i><span>設定</span></a>
              <ul class="">
                <li><a class="nav-link" href="{% url 'setting:blacklist-word' %}"><i class="fas fa-ban"></i>除外設定</a></li>
                <li><a class="nav-link" href="{% url 'setting:replace-word' %}"><i class="fas fa-sync-alt"></i>置換ワード設定</a></li>
                <li><a class="nav-link" href="{% url 'setting:profit' %}"><i class="fas fa-yen-sign"></i>利益設定</a></li>
                <li><a class="nav-link" href="{% url 'setting:common-setting' %}"><i class="fas fa-sliders-h"></i>出品共通項目設定</a></li>
              </ul>
            </li> {% endcomment %}

            {% comment %} <div class="mt-4 mb-4 p-3 hide-sidebar-mini ">
              <a href="{% url 'mypage:manual' %}" class="btn btn-primary btn-lg btn-block btn-icon-split">
                <i class="fas fa-book-open"></i> マニュアル
              </a>
            </div> {% endcomment %}
          </ul>
        </aside>
      </div>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          {% block contents %}{% endblock %}
        </section>
      </div>
      <footer class="main-footer">
        <AY-Selling class="footer-left">
          稼ぎMAX 2021
    </div>
    <div class="footer-right">
      1.0.0
    </div>
    </footer>
  </div>
  </div>

  <!-- General JS Scripts -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.js"></script>
  <script>bsCustomFileInput.init();</script>

  <!-- JS Libraies -->
  <script>
    window.jQuery || document.write('<script src="/static/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')
  </script>
  <!-- Template JS File -->
  <script src="{% static 'assets/js/scripts.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>
  <script src="{% static 'js/jquery.DOMWindow.js' %}"></script>
  <script src="{% static 'js/saveForm.js' %}"></script>

  <!-- Page Specific JS File -->
  {%block script%}{%endblock%}
</body>
{% include "modal.html" %}

</html>

app/templates/modal.html
{% load render_table from django_tables2 %}


{% ifequal modal "disp_asin_result" %}
<!-- ASIN取得結果 -->
<!-- バリエーション情報 -->
<div class="modal fade" id="variationmodal" tabindex="-1"
role="dialog" aria-labelledby="label1" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="label1">バリエーション情報</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% render_table table2  %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
</div>
<!-- フィルタ設定 -->
<div class="modal fade" id="modal1" tabindex="-1"
role="dialog" aria-labelledby="label1" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="label1">フィルタ設定</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form class="form-horizontal">
                <div class="form-group row">
                    <div class="col">
                        <label>最安値_価格</label>
                    </div>
                    <div class="col">
                        <input type="number" id="lowestPriceStart" class="form-control" placeholder="Start"/>
                    </div>

                    <div class="col">
                        <input type="number" id="lowestPriceEnd" class="form-control" placeholder="End"/>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <label>最安値_価格_FBM</label>
                    </div>
                    <div class="col">
                        <input type="number" id="lowestPriceFbmStart" class="form-control" placeholder="Start"/>
                    </div>

                    <div class="col">
                        <input type="number" id="lowestPriceFbmEnd" class="form-control" placeholder="End"/>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <label>最安値_価格_FBA</label>
                    </div>
                    <div class="col">
                        <input type="number" id="lowestPriceFbaStart" class="form-control" placeholder="Start"/>
                    </div>

                    <div class="col">
                        <input type="number" id="lowestPriceFbaEnd" class="form-control" placeholder="End"/>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" id="modalOk">OK</button>
        </div>
        </div>
    </div>
</div>

{% endifequal %}